### ISSUE TITLE
Not working - "Unfollow People Who are Following You" and all others having an issue as well

### ISSUE THREAD

**Issue by Singapore-Tech-Entrepreneurs** [Singapore-Tech-Entrepreneurs/LinkedIn-Unfollower#6]
<img width="1261" alt="screen shot 2018-07-12 at 7 24 51 pm" src="https://user-images.githubusercontent.com/31100945/42630446-570fcf14-8609-11e8-8141-05cc9fcac0b5.png">

**Comment by ronengreen** [comment]
@Singapore-Tech-Entrepreneurs 
pls elevate the permission for me in order to have a  pull-request  for this issue ,
